---
- name: Install
  ansible.builtin.package:
    name:
      - git
    state: latest
  become: false 

# - name: Install Rebase-Editor
#   community.general.npm:
#     name: rebase-editor
#     global: true
#   become: false

- name: Copy .gitconfig
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gitconfig"
    src: .gitconfig

- name: Set signinkey
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ git_user_signinkey }}"

- name: Set user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Set user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

