---
- name: Existing install
  stat:
    path: "/usr/local/bin/brew"
  register: install

- name: Download Homebrew 
  get_url:
    validate_certs: false
    dest: /tmp/homebrew-install.sh
    mode: 0755
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh 
  when: not install.stat.exists

- name: Execute homebrew-install.sh
  shell: /tmp/homebrew-install.sh
  when: not install.stat.exists

- name: Remove homebrew-install.sh
  file:
    path: /tmp/homebrew-install.sh
    state: absent
  when: not install.stat.exists

- name: Install Homebrew packages
  community.general.homebrew:
    name: 
      - gi
      - bat
      - exa
      - fd
      - fzf
      - git
      - jq
      - make
      - neovim
      - nmap 
      - node
      - nvm 
      - procs
      - ripgrep
      - tokei
      - tree
      - yarn
      - python@3.10
    state: latest
    install_options:
      -  
  ignore_errors: true

    
- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: 
      - alfred
      - docker
      - google-chrome
      - slack
      - visual-studio-code
      - warp
      - 1password
    state: latest
  ignore_errors: true
  when: ansible_distribution == "MacOSX"