---
- name: Existing install
  stat:
    path: "/usr/local/bin/brew"
  register: install

- name: Download Homebrew 
  get_url:
    validate_certs: false
    dest: /tmp/homebrew-install.sh
    mode: 0755
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh 
  when: not install.stat.exists

- name: Execute homebrew-install.sh
  shell: /tmp/homebrew-install.sh
  when: not install.stat.exists

- name: Remove homebrew-install.sh
  file:
    path: /tmp/homebrew-install.sh
    state: absent
  when: not install.stat.exists
